version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./src:/app
      - ./data:/app/data
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
    command: streamlit run src/app.py
    depends_on:
      - db

  test:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
      - ./pytest.ini:/app/pytest.ini
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
      - DB_HOST=db
    depends_on:
      - db
    command: >
      sh -c "
        echo 'Waiting for database...' &&
        sleep 5 &&
        pytest
      "

  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 
